### PR TITLE
Issue #6: Added shields to the README file.

### LINKED ISSUE #6: Add shields to README
See https://github.com/open-horizon-services/service-homeassistant for an example of shields to add

### PR DESCRIPTION
**Pull request by julianchen215**
I added shields and contributors to the read me file.
Signed-off-by: Julian Chen <julianchen435@gmail.com>

### CODE REVIEW

**Review by joewxboy — CHANGES_REQUESTED** [review]
Thanks.  Can you also please add the license shield like https://github.com/open-horizon-services/service-homeassistant has in the README?

**Comment by julianchen215** [comment]
> 
Hi @joewxboy, it seems like this repository does not have a license. When I try to add a license shield to the README file, the icon would say "license not specified".

**Comment by joewxboy** [comment]
Thanks, @julianchen215 good catch.  Could you please add the standard Apache 2.0 license file?  We shouldn't have had any commits to the repo without the license.  **oops**

It should be acceptable to copy over the LICENSE file from one of the other repos like `service-minecraft`.  Add that to this PR so the shield will work immediately.

**Comment by julianchen215** [comment]
I added LICENSE and a shield for the license.

**Pull request closed without merging**
